version: "3.8"
services:
  api:
    build: .
    depends_on:
      - db
      - db_test
    container_name: api-social
    volumes:
      - ./files:/files:rw
    ports:
      - 8000:8000
    env_file: .env
    command: >
      bash -c "wait_for db:5432 db_test:5432 && sleep 30 && entrypoint.sh"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: "true"
        fluentd-retry-wait: 1s
        fluentd-max-retries: 200
        tag: api-social.api

  db:
    image: postgres:15.2-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres-db:/var/lib/postgresql/data
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: "true"
        fluentd-retry-wait: 1s
        fluentd-max-retries: 200
        tag: api-social.db

  db_test:
    image: postgres:15.2-alpine
    container_name: db_test
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}_test
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  fluentd:
    container_name: fluentd
    image: fluentd:v1.16-1
    ports:
      - 24224:24224
      - 24224:24224/udp
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf:ro
      - ./src/logs:/fluentd/log:rw
    command: >
      /usr/bin/fluentd -c /fluentd/etc/fluent.conf -v
    networks:
      - default
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: "true"
        fluentd-retry-wait: 1s
        fluentd-max-retries: 200
        tag: api-social.fluentd

volumes:
  postgres-db:
