version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    container_name: fast-api-social-api
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgres://postgres@db
    env_file:
      - "./.env"
  postgres:
    image: postgres
    env_file:
      - "./.env"
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=fast_api_dev
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
