version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    container_name: fast-api-social-api
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgres://postgres@db
    env_file:
      - "./.env"

  postgres:
    image: postgres:15.2-alpine
    container_name: fast-api-social-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
